apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  id: {{.Values.component.id}}
  name: {{.Values.component.name}}
  functionalBlock: {{.Values.component.functionalBlock}}
  publicationDate: {{.Values.component.publicationDate}}
  status: specified
  version: {{.Values.component.version}}
  description: "Simple Product Catalog ODA-Component from Open-API reference implementation."

  maintainers:
  - name: Lester Thomas
    email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com     
  coreFunction:
    exposedAPIs: 
    - name: productcatalogmanagement
      specification: ["https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json"]
      implementation: {{.Release.Name}}-prodcatapi
      apiType: openapi
      apiKeyVerification:
        enabled: {{ .Values.component.api.apiKeyVerification.enabled }}
        location: {{ .Values.component.api.apiKeyVerification.location }}
      rateLimit:
        enabled: {{ .Values.component.api.rateLimit.enabled }}
        identifier: {{ .Values.component.api.rateLimit.identifier }}
        limit: {{ .Values.component.api.rateLimit.limit }}
        interval: {{ .Values.component.api.rateLimit.interval }}
      OASValidation:
        requestEnabled: {{ .Values.component.api.OASValidation.requestEnabled }}
        responseEnabled: {{ .Values.component.api.OASValidation.responseEnabled }}
      CORS:
        enabled: {{ .Values.component.api.CORS.enabled }}
        allowCredentials: {{ .Values.component.api.CORS.allowCredentials }}
        allowOrigins: {{ .Values.component.api.CORS.allowOrigins }}
        handlePreflightRequests:
          enabled: {{ .Values.component.api.CORS.handlePreflightRequests.enabled }}
          allowHeaders: {{ .Values.component.api.CORS.handlePreflightRequests.allowHeaders }}
          allowMethods: {{ .Values.component.api.CORS.handlePreflightRequests.allowMethods }}
          maxAge: {{ .Values.component.api.CORS.handlePreflightRequests.maxAge }}
      template: "{{ .Values.component.api.template }}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4/docs
      port: 8080
    - name: promotionmanagement
      specification: ["https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json"]
      implementation: {{.Release.Name}}-promgmtapi
      apiType: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/promotionManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/promotionManagement/v4/docs
      port: 8080      
    dependentAPIs: 
    - name: downstreamproductcatalog 
      apiType: openapi     
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction: 
    exposedAPIs: 
    - name: metrics
      apiType: prometheus
      apiKeyVerification:
        enabled: {{ .Values.component.api.apiKeyVerification.enabled }}
        location: {{ .Values.component.api.apiKeyVerification.location }}
      rateLimit:
        enabled: {{ .Values.component.api.rateLimit.enabled }}
        identifier: {{ .Values.component.api.rateLimit.identifier }}
        limit: {{ .Values.component.api.rateLimit.limit }}
        interval: {{ .Values.component.api.rateLimit.interval }}
      OASValidation:
        requestEnabled: {{ .Values.component.api.OASValidation.requestEnabled }}
        responseEnabled: {{ .Values.component.api.OASValidation.responseEnabled }}
      CORS:
        enabled: {{ .Values.component.api.CORS.enabled }}
        allowCredentials: {{ .Values.component.api.CORS.allowCredentials }}
        allowOrigins: {{ .Values.component.api.CORS.allowOrigins }}
        handlePreflightRequests:
          enabled: {{ .Values.component.api.CORS.handlePreflightRequests.enabled }}
          allowHeaders: {{ .Values.component.api.CORS.handlePreflightRequests.allowHeaders }}
          allowMethods: {{ .Values.component.api.CORS.handlePreflightRequests.allowMethods }}
          maxAge: {{ .Values.component.api.CORS.handlePreflightRequests.maxAge }}
      template: "{{ .Values.component.api.template }}"
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000    
  securityFunction:
    controllerRole: {{ .Values.security.controllerRole }}
    exposedAPIs: 
    - name: partyrole
      specification: ["https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json"]
      implementation: {{.Release.Name}}-partyroleapi
      apiType: openapi
      apiKeyVerification:
        enabled: true
        location: "header"
      rateLimit:
        enabled: false
        identifier: "IP"
        limit: "6"
        interval: "pm"
      quota:
        identifier: ""
        limit: ""
      OASValidation:
        requestEnabled: false
        responseEnabled: false
        allowUnspecifiedHeaders: false
        allowUnspecifiedQueryParams: false
        allowUnspecifiedCookies: false
      CORS:
        enabled: false
        allowCredentials: false
        allowOrigins: "https://allowed-origin.com, https://allowed-origin2.com"
        handlePreflightRequests:
          enabled: false
          allowHeaders: "Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
          allowMethods: "GET, POST"
          maxAge: 36000
      template: ""
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      port: 8080
